[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "hypermvp"
dynamic = ["version"]
license = "MIT"
readme = "README.md"
dependencies = [
    "et_xmlfile==2.0.0",
    "numpy==2.1.3",
    "openpyxl==3.1.5",
    "pandas==2.2.3",
    "pytest==7.1.0",
    "python-dateutil==2.9.0.post0",
    "pytz==2024.2",
    "six==1.16.0",
    "tzdata==2024.2",
]

[tool.hatch.version]
path = "src/hypermvp/__init__.py"

[tool.hatch.build.targets.sdist]
include = [
    "/src",
]
