name: Test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -e .
      
      - name: Create data directories
        run: |
          mkdir -p data/01_raw/afrr
          mkdir -p data/02_processed
          mkdir -p data/03_output/duckdb
      
      - name: Run tests
        run: |
          pytest
